name: todo-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      
      - name: Run CI pipeline
        run: echo "Starting CI/CD pipeline for todo-backend"
      
      - name: checkout
        uses: actions/checkout@v7

      - name: list files
        run: ls
